#####################
# Font
#####################

font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto

font_size 15.0

#####################
# Window
#####################

window_padding_width 12

background_opacity 0.94

#####################
# Cursor
#####################

shell_intergration no-cursor
cursor_shape block
cursor_blink_interval 0

#####################
# Clipboard
#####################

copy_on_select yes

#####################
# Scrollback
#####################

scrollback_lines 100000

#####################
# Colors
#####################

foreground #E7EEF0
background #2A2F2E

selection_foreground #2A2F2E
selection_background #AFC3CA

cursor #E7EEF0
cursor_text_color #2A2F2E

color0  #2A2F2E
color1  #C86D52
color2  #768C65
color3  #D3A66B
color4  #8EA5AE
color5  #A98B9F
color6  #7AA5A8
color7  #D7E1E3

color8  #5A6466
color9  #D98468
color10 #8EA374
color11 #E0B985
color12 #AFC3CA
color13 #BDA788
color14 #98BCC0
color15 #FFFFFF
